// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwpwevjrpgfnuubxqpye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3cHdldmpycGdmbnV1YnhxcHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjYxOTgsImV4cCI6MjA2NTYwMjE5OH0.iVREsmvOE9_aV8Qy8_G04XBOnKzKxaG16HNVgefcTZY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);